### ISSUE TITLE
Permissions Error | Incorrect Badge

### ISSUE THREAD

**Issue by kimstacy** [GoogleChromeLabs/adventure-issues#1]
Hello! 👋🏻. 

Despite logging into CDS Adventure through the emailed invitation link, the character is assigned a **Visitor** badge instead of **Attendee**. 

I've gone through the FAQ and have checked all steps.
 - **Current Badge:** Visitor
 - **Chat:** Enabled
 - **Global Game Chat:** Enabled, as peers will send greetings
 - **Chat Hours:** Open
 - **Mod Mute:** Off

 - **Email:** Sent 

Contacting chrome-dev-summit-adventure@google.com returns a `Delivery Status Notification (Failure)`. 

Please let me know if I can do anything to help fix this. Thank you very much!

![FAQ](https://user-images.githubusercontent.com/46656072/101681580-f8f6ee00-3a27-11eb-92c7-52612c78e4a6.png)

![Email Bounce](https://user-images.githubusercontent.com/46656072/101681958-905c4100-3a28-11eb-9d69-b45dd6dc3928.png)

**Comment by kiewic** [comment]
Same here, in addition, the email provided in the FAQs, chrome-dev-summit-adventure@google.com , doesn't seem to work.

**Comment by kimstacy** [comment]
This issue was resolved. Thank you!

My Adventure status was upgraded yesterday. I now have full chat access.

@kiewic Are you still experiencing this issue? I emailed [chrome-dev-summit@google.com](mailto:chrome-dev-summit@google.com) and received a helpful response. 

Please let me know how that goes for you!
